### ISSUE TITLE
As a new user, I want to sign up and create my user account so that I can login to my personal account.

### ISSUE THREAD

**Issue by lguebeli** [sopra-fs24-group-29/rapidhabit-server#1]
## Acceptance Criteria:
- After successful registration, users are automatically navigated to the dashboard page
- Users can not register with a username that is already taken
- Users can logout and login with their chosen credentials.

- [x] sopra-fs24-group-29/rapidhabit-client#33
- [x] sopra-fs24-group-29/rapidhabit-client#34
- [x] sopra-fs24-group-29/rapidhabit-client#32
- [x] sopra-fs24-group-29/rapidhabit-client#31
- [x] sopra-fs24-group-29/rapidhabit-server#16
- [x] sopra-fs24-group-29/rapidhabit-server#55
- [x] sopra-fs24-group-29/rapidhabit-server#56
