### ISSUE TITLE
As a user, I want to view the group and my statistics, so that I can stay motivated and informed.

### ISSUE THREAD

**Issue by lguebeli** [sopra-fs24-group-29/rapidhabit-server#10]
## Acceptance Criteria:
- Users see a statistic overview of the  days on which the group completed all habits.
- Users can see the day-streak for each habit achieved as a group.
- Users can simultaneously see the status of the other users for each habit.

- [x] sopra-fs24-group-29/rapidhabit-server#41
- [x] sopra-fs24-group-29/rapidhabit-client#11
- [x] sopra-fs24-group-29/rapidhabit-client#13
