### ISSUE TITLE
As a user, I want to be able to fill out the "Pulse Check" form and receive a notification when the rest of the group is finished as well. And I want to compare my Answers with the rest of the group.

### ISSUE THREAD

**Issue by lguebeli** [sopra-fs24-group-29/rapidhabit-server#11]
## Acceptance Criteria:
- Users receive a notification to fill out the "Pulse Check" form once in a week (randomized).
- Users have 1 hour time to fill out their "Pulse Check" or they will drop Points.
- After one hour the forms are displayed and can be compared by the users.

- [x] sopra-fs24-group-29/rapidhabit-server#44
- [x] sopra-fs24-group-29/rapidhabit-client#12
- [x] sopra-fs24-group-29/rapidhabit-server#46
