### ISSUE TITLE
As a user, I want to receive notifications when someone in my group completes a habit so that I can stay updated and motivated by our collective achievements.

### ISSUE THREAD

**Issue by lguebeli** [sopra-fs24-group-29/rapidhabit-server#12]
## Acceptance Criteria:
- Users receive notifications when a group member completes a habit.
- Notifications include relevant details such as the name of the member and the completed habit.
- Users can check the updated group Dashboard and verify the new changes.

- [x] sopra-fs24-group-29/rapidhabit-client#17
- [x] sopra-fs24-group-29/rapidhabit-server#48
- [x] sopra-fs24-group-29/rapidhabit-client#18
- [x] sopra-fs24-group-29/rapidhabit-client#38
