### ISSUE TITLE
As a group administrator, I want to manage my group’s settings and members so that I can ensure a positive and supportive tracking environment.

### ISSUE THREAD

**Issue by lguebeli** [sopra-fs24-group-29/rapidhabit-server#13]
## Acceptance Criteria:
- Admins are able to see an overview of all users in the group.
- The group administrator can change the group’s settings.
- The group administrator can add or remove members.

- [x] sopra-fs24-group-29/rapidhabit-client#19
- [x] sopra-fs24-group-29/rapidhabit-server#52
- [x] sopra-fs24-group-29/rapidhabit-server#51
