### ISSUE TITLE
As a user, I want to be able to see all groups I am assigned to and to inspect my Profile Page, where I can change my Data.

### ISSUE THREAD

**Issue by lguebeli** [sopra-fs24-group-29/rapidhabit-server#2]
## Acceptance Criteria:
- Users can see an overview of their assigned groups with the group name and group description.
- Users are able to see a button to create new groups and see a field where they can enter an existing group code to join a group.
- On the Users Profile Page a user can change his password and delete his account.

- [x] sopra-fs24-group-29/rapidhabit-server#17
- [x] sopra-fs24-group-29/rapidhabit-server#18
- [x] sopra-fs24-group-29/rapidhabit-server#19
- [x] #91
- [x] #89
- [x] #77
- [x] sopra-fs24-group-29/rapidhabit-client#6
- [x] sopra-fs24-group-29/rapidhabit-client#7
- [x] sopra-fs24-group-29/rapidhabit-client#8
- [x] #90
