### ISSUE TITLE
As a user, I want to be able to create groups and invite other users to join these groups.

### ISSUE THREAD

**Issue by lguebeli** [sopra-fs24-group-29/rapidhabit-server#3]
## Acceptance Criteria:
- Users which create a group are automatically the administrator of this group
- Group administrators can set a group name and group description.
- Users can invite other users to join the group by sending a group specific code.

- [x] sopra-fs24-group-29/rapidhabit-server#61
- [x] sopra-fs24-group-29/rapidhabit-server#62
- [x] sopra-fs24-group-29/rapidhabit-server#63
- [x] sopra-fs24-group-29/rapidhabit-server#64
- [x] sopra-fs24-group-29/rapidhabit-client#14
- [x] sopra-fs24-group-29/rapidhabit-client#15
- [x] sopra-fs24-group-29/rapidhabit-client#16
