### ISSUE TITLE
As a user, I want to be able to join a group so that I can participate in collaborative habit tracking.

### ISSUE THREAD

**Issue by lguebeli** [sopra-fs24-group-29/rapidhabit-server#4]
## Acceptance Criteria:
- Users can join a group by using their invitation code and enter it on their dashboard.
- Users receive a confirmation of success after joining a new group.
- Users can see the success of the other users in the group after joining a new group

- [x] sopra-fs24-group-29/rapidhabit-server#23
- [x] sopra-fs24-group-29/rapidhabit-client#37
- [x] sopra-fs24-group-29/rapidhabit-client#35
- [x] sopra-fs24-group-29/rapidhabit-client#20
- [x] sopra-fs24-group-29/rapidhabit-client#21
- [x] sopra-fs24-group-29/rapidhabit-client#22
