### ISSUE TITLE
As an Admin, I want to select from predefined habits to add to my tracking list for guidance and to ensure I am focusing on beneficial routines.

### ISSUE THREAD

**Issue by lguebeli** [sopra-fs24-group-29/rapidhabit-server#5]
## Acceptance Criteria:
- Admins can browse a list of predefined habits.
- After selection the habit is added to the group dashboard.
- Predefined habits can be edited or deleted.

- [x] sopra-fs24-group-29/rapidhabit-server#26
- [x] #78
- [x] sopra-fs24-group-29/rapidhabit-server#28
- [x] sopra-fs24-group-29/rapidhabit-client#23
- [x] sopra-fs24-group-29/rapidhabit-client#25
