### ISSUE TITLE
As an Admin, I want to create habits for the group which fit our specific goals and add them to our group dashboard.

### ISSUE THREAD

**Issue by lguebeli** [sopra-fs24-group-29/rapidhabit-server#6]
## Acceptance Criteria:
- Admins can use a form to create a new group habit.
- For each of these habits admins can choose a name, description, frequency and achievable points.
- Admins can edit or delete other group habits.

- [x] sopra-fs24-group-29/rapidhabit-server#29
- [x] #93
- [x] #94
- [x] sopra-fs24-group-29/rapidhabit-server#30
- [x] #107
- [x] sopra-fs24-group-29/rapidhabit-server#31
- [x] sopra-fs24-group-29/rapidhabit-client#26
- [x] sopra-fs24-group-29/rapidhabit-client#27
