### ISSUE TITLE
As a User, I want to receive feedback from the AI coach in the feed so that I can understand how I am doing and how to improve my progress.

### ISSUE THREAD

**Issue by lguebeli** [sopra-fs24-group-29/rapidhabit-server#7]
## Acceptance Criteria:
- User receives personalized feedback from the AI coach based on their performance and habit tracking.
- AI coach provides suggestions for improvement and encouragement to enhance user motivation.
- Feedback from AI coach is presented in a clear, friendly, and supportive manner.

- [x] sopra-fs24-group-29/rapidhabit-server#32
- [x] sopra-fs24-group-29/rapidhabit-client#28
- [x] sopra-fs24-group-29/rapidhabit-server#34
