### ISSUE TITLE
As a user, I want to view the group dashboard to see the progress of the group and myself. And communicate with each other about our progress.

### ISSUE THREAD

**Issue by lguebeli** [sopra-fs24-group-29/rapidhabit-server#8]
## Acceptance Criteria:
- Users can see all tracked habits and check which have been completed and which are still pending.
- Users can see recent activities and updates from their group members.
- Users can chat with each other, and discuss their progress.
- Users can navigate to different sections of the dashboard.

- [x] sopra-fs24-group-29/rapidhabit-server#35
- [x] sopra-fs24-group-29/rapidhabit-client#5
- [x] sopra-fs24-group-29/rapidhabit-server#37
- [x] #113
- [x] #114
- [x] #115
- [x] sopra-fs24-group-29/rapidhabit-client#9
