### ISSUE TITLE
As a user, I want to view my personal ranking to see the progress of myself com- pared to the other group members.

### ISSUE THREAD

**Issue by lguebeli** [sopra-fs24-group-29/rapidhabit-server#9]
## Acceptance Criteria:
- Users get predefined points for each habit they have completed.
- Users can see their ranking compared to the other group members.
- Users can see their total points.

- [x] sopra-fs24-group-29/rapidhabit-server#38
- [x] sopra-fs24-group-29/rapidhabit-client#10
- [x] sopra-fs24-group-29/rapidhabit-server#40
